### ISSUE TITLE
Issue with new environment installation

### ISSUE THREAD

**Issue by mabbasi6** [QI2lab/merfish3d-analysis#31]
* wf-merfish push version: 783ab16
* Python version: 3.10
* Operating System: Linux

### Description

Hi,

Just tried installing the latest environment and package and noticed 2 issues:
1. "pyproject.toml" line 23 needs "git+" for "pycudadecon" installation
2. After fixing it, installing the package, and running postprocessing, got an error saying "tensorstore" is missing:
`    from merfish3danalysis.postprocess.postprocess import postprocess
  File "/home/momo/Repos/merfish3d-analysis/src/merfish3danalysis/postprocess/postprocess.py", line 43, in <module>
    from merfish3danalysis.utils._dataio import return_data_zarr, read_metadatafile, resave_baysor_output
  File "/home/momo/Repos/merfish3d-analysis/src/merfish3danalysis/utils/_dataio.py", line 22, in <module>
    import tensorstore as ts
ModuleNotFoundError: No module named 'tensorstore'`

Thank you.

**Comment by mabbasi6** [comment]
@dpshepherd

**Comment by dpshepherd** [comment]
closed by 00ff209
